# Stubs for mersad.test.util.test_string_analyzer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest

class TestLetterIndexMapper(unittest.TestCase):
    def test_short_string(self) -> None: ...

class TestLetterIndexFinder(unittest.TestCase):
    def test_short_string(self) -> None: ...
