default:
  image: python:3.6.8
  # before_script:

stages:
  - test
  - release

# job for testing package on master branch
# and send tet coverage to codeclimate.
test_master:
  stage: test
  # install dependencies.
  before_script:
    # install codeclimate coverage reported.
    - script/ci_install_curl.sh
    - script/ci_install_codeclimate.sh
    # run code climate test reporter agent.
    - ./cc-test-reporter before-build
    # install pipenv.
    - pip3 install pipenv
    # install pipfile.
    - pipenv install --skip-lock
    - pipenv install --dev --skip-lock
  # run tests.
  script:
    - script/ci_test.sh
  # send results to codeclimate.
  after_script:
    - ./cc-test-reporter after-build --coverage-input-type coverage.py
  only:
    - master

# job for testing package on other branches
# and merge requests.
test_branches:
  stage: test
  # install dependencies.
  before_script:
    # install pipenv.
    - pip3 install pipenv
    # install pipfile.
    - pipenv install --skip-lock
    - pipenv install --dev --skip-lock
  # run tests.
  script:
    - script/ci_test.sh
  # run on branches and merge request.
  only:
    - branches
    - merge_requests
  # don't run on master.
  except:
    - master

# deploy package to pypi whenever a tag released.
pypi:
  stage: release
  # install dependencies.
  before_script:
    - pip install twine
    - python3 setup.py sdist
  script:
    - twine upload dist/*
  # only run for new tag
  only:
    - tags
  when: manual

