default:
  image: python:3.6.8
  # before_script:

stages:
  - test
  - deploy

test:
  stage: test
  # install codeclimate coverage reported
  before_script:
    - script/ci_install_curl.sh
    - script/ci_install_codeclimate.sh
  script:
  - python3 --version
  - pip3 --version