default:
  # pull custom docker file
  image: azadehafzarhub/gitlab-ci-python-build

stages:
  - test
  - release

# job for testing package on master branch
# and send test coverage result to codeclimate.
test_master:
  stage: test
  before_script:
    # run code climate test reporter agent.
    - cc-test-reporter before-build
    # install dependencies from the pipfile.
    - pipenv install --dev
  # run tests.
  script:
    - script/test.sh
  # send test coverage result to codeclimate.
  after_script:
    - cc-test-reporter after-build --coverage-input-type coverage.py
  only:
    - master

# job for testing package on other branches
# and merge requests.
test_branches:
  stage: test
  # install dependencies.
  before_script:
    # install dependencies from the pipfile.
    - pipenv install --dev
  # run tests.
  script:
    - script/test.sh
  # run on branches and merge requests.
  only:
    - branches
    - merge_requests
  # don't run on master branch.
  except:
    - master

# deploy package to pypi whenever a tag is released.
release_pypi:
  stage: release
  # install dependencies.
  before_script:
    - python3 setup.py sdist
  script:
    - twine upload dist/*
  # only run for new tags.
  only:
    - tags
  when: manual
