language: python
python:
  - "3.6"
# install dependencies
install:
  - pipenv install --skip-lock
  - pipenv install --dev --skip-lock

# install codeclimate coverage reported
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# run tests
script:
  - script/ci_test.sh

# send results to codeclimate
after_script:
  - echo $TRAVIS_TEST_RESULT
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT