# Stubs for mersad.classical (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# Names in __all__ with no definition:
#   affine_cipher
#   atbash_cipher
#   mixalph_cipher
#   shift_cipher
