# Stubs for mersad.classical.affine_cipher (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# Python Standard Library
import argparse
from typing import Any
from typing import Tuple

# Mersad Library
from mersad.util.base_class import KWARGS_TYPE
from mersad.util.base_class import MersadClassicalBase
from mersad.util.terminal_app_tools import MainFunctionClassical

def main(argv: Tuple[str]=...) -> None: ...

class AffineCipher(MersadClassicalBase):
    def _config_subroutines(self, **kwargs: KWARGS_TYPE) -> None: ...
    @staticmethod
    def _translator(text: str, **kwargs: KWARGS_TYPE) -> str: ...

def affine_cipher_translator(text: str, **kwargs: KWARGS_TYPE) -> str: ...
def _check_keys(key_a: int, sequence_length: int) -> None: ...

class AffineCipherMainFunction(MainFunctionClassical):
    def _config_agent(self, agent: Any, args: argparse.Namespace) -> None: ...
    def _custom_arguments(self) -> argparse.ArgumentParser: ...
