# Stubs for mersad.classical.atbash_cipher (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# Python Standard Library
import argparse
from typing import Any
from typing import Tuple

# Mersad Library
from mersad.util.base_class import KWARGS_TYPE
from mersad.util.base_class import MersadClassicalBase
from mersad.util.terminal_app_tools import MainFunctionClassical

def main(argv: Tuple[str] = ...) -> None: ...

class AtbashCipher(MersadClassicalBase):
    @staticmethod
    def _translator(text: str, **kwargs: KWARGS_TYPE) -> str: ...

def atbash_cipher_translator(text: str, **kwargs: KWARGS_TYPE) -> str: ...

class AtbashCipherMainFunction(MainFunctionClassical):
    def _config_agent(self, agent: Any, args: argparse.Namespace) -> None: ...
