# Stubs for mersad.classical.mixalph_cipher (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# Python Standard Library
import argparse
from typing import Any
from typing import Tuple
from typing import Union

# Mersad Library
from mersad.util.base_class import MersadClassicalBase
from mersad.util.terminal_app_tools import MainFunctionClassical

def main(argv: Tuple[str]=...) -> None: ...

class MixalphCipher(MersadClassicalBase):
    def show_sort_key(self) -> int: ...
    def _init_subroutines(self) -> None: ...
    def _config_subroutines(self, **kwargs: Union[int, str, bool]) -> None: ...
    @staticmethod
    def _translator(text: str, **kwargs: Union[int, str, bool]) -> str: ...

def mixalph_cipher_translator(text: str, **kwargs: Union[int, str, bool]) -> str: ...

class MixalphCipherMainFunction(MainFunctionClassical):
    def _config_agent(self, agent: Any, args: argparse.Namespace) -> None: ...
    def _custom_arguments(self) -> argparse.ArgumentParser: ...
