# Stubs for mersad.classical.route_cipher (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# Python Standard Library
import argparse
from typing import Any
from typing import Dict
from typing import Tuple

# Mersad Library
from mersad.util.base_class import KWARGS_TYPE
from mersad.util.base_class import MersadClassicalBase
from mersad.util.terminal_app_tools import MainFunctionClassical

def main(argv: Tuple[str]=...) -> None: ...

class RouteCipher(MersadClassicalBase):
    def _init_subroutines(self) -> None: ...
    def _config_subroutines(self, **kwargs: KWARGS_TYPE) -> None: ...
    def _process_subroutines(self, configurations: Dict[str, KWARGS_TYPE], **kwargs: KWARGS_TYPE) -> Dict[str, KWARGS_TYPE]: ...
    @staticmethod
    def _translator(text: str, **kwargs: KWARGS_TYPE) -> str: ...

def route_cipher_translator(text: str, **kwargs: KWARGS_TYPE) -> str: ...

class RouteCipherMainFunction(MainFunctionClassical):
    def _config_agent(self, agent: Any, args: argparse.Namespace) -> None: ...
    def _custom_arguments(self) -> argparse.ArgumentParser: ...
