# Stubs for mersad.util.base_class (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# Python Standard Library
from typing import Any
from typing import Dict
from typing import List
from typing import Optional
from typing import Union

KWARGS_TYPE = Union[int, str, bool, List[int]]

class MersadClassicalBase:
    _defaults: Any = ...
    configuration: Any = ...
    def __init__(self, **kwargs: KWARGS_TYPE) -> None: ...
    def __str__(self) -> str: ...
    def encrypt(
        self,
        plain_text: str,
        key: Optional[int] = ...,
        replace_key: bool = ...,
        **kwargs: KWARGS_TYPE,
    ) -> str: ...
    def decrypt(
        self,
        cipher_text: str,
        key: Optional[int] = ...,
        replace_key: bool = ...,
        **kwargs: KWARGS_TYPE,
    ) -> str: ...
    def config(self, **kwargs: KWARGS_TYPE) -> None: ...
    def reset(self) -> None: ...
    def show_key(self) -> int: ...
    def _process(
        self,
        text: str,
        key: Optional[int],
        replace_key: bool,
        decrypt: bool,
        **kwargs: KWARGS_TYPE,
    ) -> str: ...
    def _init_subroutines(self) -> None: ...
    def _config_subroutines(self, **kwargs: KWARGS_TYPE) -> None: ...
    def _process_subroutines(
        self, configurations: Dict[str, KWARGS_TYPE], **kwargs: KWARGS_TYPE
    ) -> Dict[str, KWARGS_TYPE]: ...
    @staticmethod
    def _translator(text: str, **kwargs: KWARGS_TYPE) -> str: ...
